services:
  - type: web
    name: snipeit-app
    env: docker
    plan: free
    disk:
      name: snipeit-storage
      mountPath: /var/lib/snipeit
      sizeGB: 1
    envVars:
      - key: APP_DEBUG
        value: "true"
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: snipeit-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: snipeit-postgres
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: snipeit-postgres
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: snipeit-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: snipeit-postgres
          property: password
      - key: APP_KEY
        generateValue: true

databases:
  - name: snipeit-postgres
    plan: free
